### PR TITLE
Handle potentially truncating snprintf

### PR DESCRIPTION
**Pull request by afreof**
GCC8 with -Werror=format-truncation fails on lines such as
  snprintf (name, sizeof (name), "%s/%s/size"...

### CODE REVIEW

**Comment by jogness** [comment]
This patch is **not** handling truncation. snprintf truncates when the return value is greater than or equal to the size of the buffer. Less than zero is for errors. I consider this patch dangerous because it is ignoring the truncation case (which was the reason gcc8 started checking this).

**Comment by afreof** [comment]
Thank you for reviewing the patch. I absolutely agree with your remarks.

There is now a Force Push update of my patch. Unfortunately, the new patch is much more complex just to solve a very unlikely corner case. So far, I haven't found an easy way to test the error handling code. The regular use case works as it did without this patch, at least in our test setup.
Before it gets merged, it should be reviewed carefully.

**Comment by jogness** [comment]
The new version correctly handles the snprint issue. However, the patch also adds some extra (necessary) error handling related to memory cleanup. And here you have an error...

If calloc() fails, it is not enough to free namelist.  You need to free all nr entries first. It would probably be more appropriate to have an extra goto that jumps after the free(map) in the error handling.

**Comment by afreof** [comment]
I've been thinking about that, too. But this case has not been handled before either.
I have not executed this version on hardware yet. I will do so tomorrow. Does it look right to you now?

**Comment by jogness** [comment]
Looks good to me. For a153f0eb1a06bdac9f67185ec5c5e6d9b2c19ab6 feel free to add:

Reviewed-by: John Ogness <john.ogness@linutronix.de>

**Comment by jogness** [comment]
By the way, to test the code, just change name[PATH_MAX] to name[5] or something.

**Comment by afreof** [comment]
Thank you John. At least the tests executed by our automated test system have been passed with this patch applied. I think this is ready for merging now.

**Pull request merged**
